# mkdocs.yml
#
# This is the primary configuration file for a Materials for MkDocs website,
# tailored as a template for Dartmouth College faculty members or students.
# It defines the site's metadata, theme settings, navigation structure,
# Markdown extensions, and custom assets (CSS, JavaScript).
#
# To use this template:
# 1. Replace all placeholder values (e.g., [Your Name], [your-website.dartmouth.edu]).
# 2. Ensure your custom assets (logo, favicon, fonts, extra.css, extra.js)
#    are placed in the correct directories as indicated by the paths.
# 3. Customize the 'nav' section to reflect your site's content structure.
# 4. For detailed documentation on any setting, refer to:
#    https://squidfunk.github.io/mkdocs-material/setup/
#
#---------------------------------------------------------------------------------------------------
# 1. Site Information                                                                               #
#    These settings define basic metadata about your website.                                       #
#---------------------------------------------------------------------------------------------------
site_name: Your Name | Your Title/Department/Program            # The title of your website, displayed in the browser tab and header.
                                                                # Example: "Jane Doe | Professor of Computer Science" or "John Smith | PhD Candidate in Chemistry"
site_url: https://your-website.dartmouth.edu                            # The base URL where your site will be hosted (e.g., https://janedoe.host.dartmouth.edu).
                                                                # Essential for sitemaps and canonical URLs.
site_author: Your Name                                          # The author of the site, often used in meta tags.
site_description: A brief description of your website's purpose # A brief description for SEO and browser display.
                                                                # Example: "Personal website of [Your Name], focusing on research in [field]."

#---------------------------------------------------------------------------------------------------
# 2. Theme Configuration                                                                            #
#    This section configures the visual theme of your website.                                      #
#---------------------------------------------------------------------------------------------------
theme:
  name: material                                      # Specifies "Materials for MkDocs" as the theme.
  custom_dir: overrides                               # Points to a directory for theme customizations.
                                                      # Files in this directory (e.g., main.html, base.html) will override
                                                      # corresponding theme files, allowing advanced modifications.
  logo: assets/images/dartmouth-logo.png              # Path to your site's logo, displayed in the header.
                                                      # Relative to the 'docs' directory (e.g., docs/assets/images/).
                                                      # You can replace this with your own logo or a generic Dartmouth logo.
  favicon: assets/images/favicon.ico                  # Path to your site's favicon, shown in browser tabs.
                                                      # Relative to the 'docs' directory.

  features:                                           # Enables various built-in features of Materials for MkDocs.
    - navigation.tabs                                 # Top-level navigation as tabs.
    - navigation.instant                              # Speeds up page loading by prefetching content.
    - toc.integrate                                   # Integrates the Table of Contents directly into the main content sidebar.
    - content.code.copy                               # Adds a "copy" button to code blocks.
    # - navigation.sections                           # Uncomment to enable collapsible sections in sidebar nav.
    # - search.suggest                                # Uncomment for search suggestions.
    # - search.highlight                              # Uncomment to highlight search results on the page.
    # NOTE: The 'footer' feature (for a built-in MkDocs-Material footer) is typically
    #       only available in the Insiders version. For the public version,
    #       a custom footer (like the one provided in extra.css) is usually implemented.

  palette:                                            # Configures color schemes (light/dark mode).
    - scheme: default                                 # Defines the default (light) color scheme.
      primary: custom                                 # 'custom' indicates colors are defined via CSS variables (in extra.css).
      accent: custom                                  # 'custom' for accent color.
      toggle:
        icon: material/weather-night                  # Icon for switching to dark mode.
        name: Switch to dark mode                     # Tooltip text for the toggle.
    - scheme: slate                                   # Defines the dark color scheme.
      primary: custom                                 # 'custom' for dark mode primary color.
      accent: custom                                  # 'custom' for dark mode accent color.
      toggle:
        icon: material/weather-sunny                  # Icon for switching to light mode.
        name: Switch to light mode                    # Tooltip text for the toggle.

  font: false                                         # VERY IMPORTANT: Set to 'false' to disable Google Fonts.
                                                      # This allows your locally hosted custom fonts (@font-face in extra.css)
                                                      # like "National 2" and "Dartmouth Ruzika" to be used without conflict.
      # text: Roboto                                  # (Commented out) If 'font: false' was not set, these would define Google Fonts.
      # code: Roboto Mono                             # (Commented out)

#---------------------------------------------------------------------------------------------------
# 3. Extra Assets (CSS and JavaScript)                                                              #
#    Links to additional CSS and JavaScript files for further customization.                        #
#---------------------------------------------------------------------------------------------------
extra_css:
  - stylesheets/extra.css                                       # Path to your custom CSS file.
                                                                # Relative to the 'docs' directory (e.g., docs/stylesheets/extra.css).
                                                                # This is where you put all your custom Dartmouth-specific styling.
extra_javascript:
  - javascripts/extra.js                                        # Path to your custom JavaScript file.
                                                                # Relative to the 'docs' directory (e.g., docs/javascripts/extra.js).
                                                                # Use this for custom interactivity (e.g., scroll-to-top button logic).
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js # Includes MathJax library for rendering LaTeX/mathematical equations.
                                                                # Essential if you use the 'pymdownx.arithmatex' extension.

#---------------------------------------------------------------------------------------------------
# 4. Extra Variables                                                                                #
#    Custom variables accessible in your theme templates and Markdown via Jinja2.                   #
#---------------------------------------------------------------------------------------------------
extra:
  generator: false                                   # Set to 'false' to hide the "Generated by MkDocs" footer message.
  social:                                            # Defines social media links, often used in custom footers.
    - icon: fontawesome/brands/google-scholar        # Example: Google Scholar profile.
      link: [Your Google Scholar Profile URL]
    - icon: fontawesome/brands/github                # Example: GitHub profile.
      link: [Your GitHub Profile URL]
    # Add more social links as needed:
    # - icon: fontawesome/brands/linkedin
    #   link: [Your LinkedIn Profile URL]
    # - icon: fontawesome/brands/twitter
    #   link: [Your Twitter Profile URL]
  description: [A short, concise description for meta tags and social sharing]  # Custom description, potentially used in templates.
                                                                                # Example: "Official academic page of [Your Name], a researcher at Dartmouth."
  image: assets/images/dartmouth-logo.png                                       # Custom image path, potentially used for social sharing cards (Open Graph).
                                                                                # Consider a profile picture or a relevant project image.

#---------------------------------------------------------------------------------------------------
# 5. Navigation Structure                                                                           #
#    Defines the main navigation menu of your site. Customize this to match your content.           #
#---------------------------------------------------------------------------------------------------
nav:
  - Home: index.md                                   # The main landing page.
  - About: about.md                                  # Information about yourself.
  - Research: research.md                             # Overview of your research interests.
  - Publications:                                    # A section for your publications.
      - Overview: publications/index.md
      - Selected Works: publications/selected.md
      - Preprints: publications/preprints.md
      - Covers: publications/covers.md
  - Teaching: teaching.md                            # Courses taught, teaching philosophy, etc. (Optional)
  - Resources: resources.md                          # Useful links, tools, or guides. (Optional)
  - Contact: contact.md                              # Contact information. (Optional)
  # - [Custom Section Title]:
  #     - [Sub-page Title 1]: path/to/page1.md
  #     - [Sub-page Title 2]: path/to/page2.md

#---------------------------------------------------------------------------------------------------
# 6. Markdown Extensions                                                                            #
#    Enables additional features and syntax for Markdown processing.                                #
#    These are generally useful for academic/technical content.                                     #
#---------------------------------------------------------------------------------------------------
markdown_extensions:
  - toc:                                             # Table of Contents extension.
      permalink: true                                # Adds a permalink icon next to headings.
      separator: "-"                                 # Character used to separate words in permalinks.
  - footnotes                                        # Enables standard Markdown footnotes.
  - admonition                                       # Enables admonition blocks (e.g., `!!! note`, `!!! warning`, `!!! info`).
  - pymdownx.details                                 # Enhances admonitions, allows collapsible <details> tags.
  - pymdownx.superfences                             # Improves code blocks, especially for syntax highlighting and nested blocks.
  - pymdownx.caret                                   # Enables `^^` syntax for highlighting text.
  - pymdownx.mark                                    # Enables `==` syntax for marking/highlighting text.
  - pymdownx.tilde                                   # Enables `~~` syntax for strikethrough text.
  - pymdownx.tasklist                                # Enables GitHub-style task lists (`- [ ]`).
  - pymdownx.snippets                                # Allows including content from other Markdown files.
  - attr_list                                        # Allows adding HTML attributes directly to Markdown elements.
  - pymdownx.arithmatex:                             # Enables advanced math rendering (LaTeX).
      generic: true                                  # Uses generic delimiters for math blocks.
      # Requires MathJax (loaded via 'extra_javascript').

#---------------------------------------------------------------------------------------------------
# 7. Plugins                                                                                        #
#    Enables MkDocs plugins that extend its functionality (e.g., search, sitemaps).                 #
#---------------------------------------------------------------------------------------------------
plugins:
  - search                                           # Enables the built-in client-side search functionality.
    # - privacy                                      # Example: A plugin for privacy-friendly analytics.
    # - social                                       # Example: A plugin for generating social media cards.
    # - sitemap                                      # Recommended for SEO. Automatically generates sitemap.xml.